name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Check Rust styles
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy --workspace -- -D warnings
  mac:
    name: Build (Mac)
    runs-on: macos-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --workspace -- -D warnings
    - name: Install x86_64-apple-darwin
      run: rustup target add x86_64-apple-darwin
    - name: Build
      run: |
        cargo build --release --target aarch64-apple-darwin
        cargo build --release --target x86_64-apple-darwin
        mkdir -p dist/bin
        lipo -create -output dist/bin/warp target/aarch64-apple-darwin/release/warp target/x86_64-apple-darwin/release/warp
    - name: Create Apple Disk Image
      run: hdiutil create -volname Warp -srcfolder dist Warp.dmg
    - name: Upload Apple Disk Image
      uses: actions/upload-artifact@v4
      with:
        name: warp-macos
        path: Warp.dmg
  windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --workspace -- -D warnings
